-- MySQL Script generated by MySQL Workbench
-- Wed Jul 15 19:26:19 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dropbox
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dropbox` ;

-- -----------------------------------------------------
-- Schema dropbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dropbox` DEFAULT CHARACTER SET utf8 ;
USE `dropbox` ;

-- -----------------------------------------------------
-- Table `dropbox`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dropbox`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `dropbox`.`Usuarios` (
  `correo` VARCHAR(50) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `pass` VARCHAR(50) NULL DEFAULT NULL,
  `ultConexion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`correo`, `login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dropbox`.`archivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dropbox`.`archivos` ;

CREATE TABLE IF NOT EXISTS `dropbox`.`archivos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `contenido` LONGBLOB NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `ultimaMod` DATE NULL DEFAULT NULL,
  `tamanio` FLOAT NULL DEFAULT NULL,
  `Usuarios_correo` VARCHAR(50) NOT NULL,
  `Usuarios_login` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `Usuarios_correo`, `Usuarios_login`),
  INDEX `fk_archivos_Usuarios_idx` (`Usuarios_correo` ASC, `Usuarios_login` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
